# Generated by Django 4.1.13 on 2024-11-25 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exercises', models.TextField()),
                ('duration', models.DurationField()),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=10)),
                ('time', models.TimeField()),
                ('room', models.CharField(default='Sala Principal', max_length=255)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.routine')),
            ],
            options={
                'unique_together': {('day', 'time', 'room')},
            },
        ),
    ]
